changelog:
  categories:
    - title: Features
      labels: [enhancement]
    - title: Bug Fixes
      labels: [bug]
    - title: Documentation
      labels: [documentation]
    - title: Chores
      labels: [chore]
    - title: Dependencies
      labels: [dependencies]
    - title: CI
      labels: [ci]
