# Development task runner — requires Just (https://just.systems)
# All commands also work without Just by running the uv commands directly.

# Show available recipes
default:
    @just --list

# The hooks are the only guard that runs for every author, so a missing one
# fails the install. ALLOW_MISSING_GIT_HOOKS=1 is the deliberate opt-out and
# CI=true (CI commits nothing) skips the failure: both still attempt the
# install, and turn a failed install or a missing hook into a warning.
# Install dependencies and the git hooks, then verify the hooks are in place
install:
    #!/usr/bin/env bash
    set -euo pipefail
    uv sync --all-groups --locked
    if ! git rev-parse --git-dir >/dev/null 2>&1; then
      echo "Skipping pre-commit hook installation (not a Git repository)."
      exit 0
    fi
    # --git-path prints a path relative to the current directory unless it is
    # absolute (a linked worktree), so resolve it from the top level.
    cd "$(git rev-parse --show-toplevel)"
    is_exempt=0
    ci=$(printf '%s' "${CI:-}" | tr '[:upper:]' '[:lower:]')
    [ "$ci" = "true" ] && is_exempt=1
    [ "${ALLOW_MISSING_GIT_HOOKS:-}" = "1" ] && is_exempt=1
    uv run --locked pre-commit install --install-hooks || [ "$is_exempt" -eq 1 ]
    # The hook types come from .pre-commit-config.yaml's flow-style
    # default_install_hook_types list; without the key pre-commit installs
    # only the pre-commit hook.
    hook_types=pre-commit
    if [ -f .pre-commit-config.yaml ] && grep -q '^default_install_hook_types:' .pre-commit-config.yaml; then
      hook_types=$(sed -n 's/^default_install_hook_types:[[:space:]]*\[\(.*\)\].*$/\1/p' .pre-commit-config.yaml | tr ',' ' ' | xargs)
      if [ -z "$hook_types" ]; then
        echo "error: .pre-commit-config.yaml's default_install_hook_types is not a one-line [a, b] list." >&2
        exit 1
      fi
    fi
    missing=""
    for hook in $hook_types; do
      path=$(git rev-parse --git-path "hooks/$hook")
      case "$path" in /*) ;; *) path="$PWD/$path" ;; esac
      if [ ! -x "$path" ] || ! grep -q "File generated by pre-commit" "$path"; then
        missing="$missing $path"
      fi
    done
    if [ -z "$missing" ]; then
      echo "Git hooks verified: $hook_types."
    elif [ "$is_exempt" -eq 1 ]; then
      echo "Warning: git hooks missing (allowed by CI=true or ALLOW_MISSING_GIT_HOOKS=1):$missing" >&2
    else
      echo "error: git hooks missing:$missing" >&2
      echo "Run 'uv run --locked pre-commit install --install-hooks', or set ALLOW_MISSING_GIT_HOOKS=1 to install without them." >&2
      exit 1
    fi

# Alias for first-time project setup
setup: install

# Format code (lint fixes first so the formatter has the last word)
fmt:
    uv run --locked ruff check --fix .
    uv run --locked ruff format .

# Run linters and type checker
lint:
    uv run --locked ruff check .
    uv run --locked ruff format --check .
    uv run --locked mypy

# Run tests in parallel with coverage
test:
    uv run --locked pytest -n auto --cov --cov-report=term-missing:skip-covered --cov-fail-under=80

# Never ends on its own; an agent starts `my-app serve --port <free>` instead and stops it.
# Human-run: serve the HTTP API on http://127.0.0.1:8000, reloading on source changes
dev:
    uv run --locked uvicorn my_app.api.app:create_app --factory --reload

# Each argument is passed through as-is, so `just run todo add "buy milk"` keeps the quotes.
# Run the my-app CLI, e.g. `just run todo list`
[positional-arguments]
run *ARGS:
    uv run --locked my-app "$@"

# Update uv.lock after changing dependency declarations
lock:
    uv lock

# Run all checks: format, lint, test
check: fmt lint test

# Non-mutating local PR gate (fail-fast: cheap gates before the suite)
verify: lock-check agents-check check-harness lint test-skills test

# tests/harness checks skills, AGENTS.md (its Skills table and Quick Reference),
# recipes, the ruleset, labels, and workflows against each other.
# tests/test_product_section.py rides along because it is the harness's (g)
# check: in an app it stays red until AGENTS.md's Product section is filled in,
# which is not drift. `just test` runs both again as part of the whole suite.
# Fail on harness drift (tests/harness) or an unfilled Product section
check-harness:
    uv run --locked pytest tests/harness tests/test_product_section.py

# Each suite stays stdlib unittest; pytest-xdist runs suites across processes.
# The .claude/skills mirror is the same bytes, so only the authored tree runs.
# Run the test suites bundled with skills (.agents/skills/*/scripts/tests)
test-skills:
    PYTHONDONTWRITEBYTECODE=1 uv run --locked pytest -n auto -p no:cacheprovider .agents/skills/*/scripts/tests

# Confirm the lockfile is current without changing it.
lock-check:
    uv lock --check

# Regenerate the .claude/skills mirror from .agents/skills (the authored copy)
agents-sync:
    uv run --locked python scripts/sync_agents.py

# Fail when .claude/skills disagrees with .agents/skills
agents-check:
    uv run --locked python scripts/sync_agents.py --check

# Create or update the GitHub labels declared in .github/labels.yml (writes to GitHub)
labels *ARGS:
    uv run --locked python scripts/sync_labels.py {{ARGS}}

# Create or update the main branch ruleset from .github/rulesets/main.json (admin-only; writes to GitHub)
ruleset *ARGS:
    uv run --locked python scripts/apply_ruleset.py {{ARGS}}

# Remove build artifacts
clean:
    rm -rf dist/ build/ .mypy_cache/ .ruff_cache/ .pytest_cache/ htmlcov/ .coverage .coverage.* coverage.xml
    find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
    find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true

# Install dependencies in a Codex-managed linked worktree without rewriting
# the shared pre-commit hook; install hooks once in the primary checkout.
worktree-prepare:
    uv sync --all-groups --locked

# Create one issue worktree using the existing shipping-issues provisioner.
worktree-setup ISSUE BRANCH BASE ROOT VERIFY:
    bash .agents/skills/shipping-issues/scripts/worktree_setup.sh --issue {{ISSUE}} --branch {{BRANCH}} --base {{BASE}} --root {{ROOT}} --verify {{VERIFY}}

# Preview cleanup of one named branch. Only merged PR heads with clean worktrees qualify.
worktree-clean ROOT BRANCH:
    uv run --locked python scripts/worktree_cleanup.py --root {{ROOT}} --branch {{BRANCH}}

# Apply the previewed cleanup of one named branch; no --force or remote deletion.
worktree-clean-apply ROOT BRANCH:
    uv run --locked python scripts/worktree_cleanup.py --root {{ROOT}} --branch {{BRANCH}} --apply
