"""Tests for the justfile's ``install`` recipe: the git-hook gate.

The recipe body is read from the justfile and run with bash in a ``tmp_path``
repository, so CI needs no ``just``. A fake ``uv`` on ``PATH`` stands in for
``uv sync`` and ``pre-commit install``: it writes a pre-commit-generated hook
for each type named in ``FAKE_INSTALL_HOOKS`` and exits ``FAKE_INSTALL_EXIT``.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from collections.abc import Callable

    type RunInstall = Callable[..., subprocess.CompletedProcess[str]]

REPO_ROOT = Path(__file__).resolve().parents[1]
JUSTFILE = REPO_ROOT / "justfile"
CONFIG = REPO_ROOT / ".pre-commit-config.yaml"

FAKE_UV = """\
#!/usr/bin/env bash
set -eu
[ "$1" = "sync" ] && exit 0
hooks=$(git rev-parse --path-format=absolute --git-path hooks)
mkdir -p "$hooks"
for hook in ${FAKE_INSTALL_HOOKS:-}; do
  printf '#!/bin/sh\\n# File generated by pre-commit: https://pre-commit.com\\n' > "$hooks/$hook"
  chmod +x "$hooks/$hook"
done
exit "${FAKE_INSTALL_EXIT:-0}"
"""


def _install_body() -> str:
    lines = JUSTFILE.read_text(encoding="utf-8").splitlines()
    start = lines.index("install:") + 1
    body: list[str] = []
    for line in lines[start:]:
        if not line.startswith("    "):
            break
        body.append(line)
    return textwrap.dedent("\n".join(body)) + "\n"


def _git(cwd: Path, *args: str) -> None:
    subprocess.run(  # noqa: S603 -- a fixed git argv, no shell
        ["git", *args],  # noqa: S607 -- git resolved from PATH, as a shell would
        cwd=cwd,
        check=True,
        capture_output=True,
    )


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    root.mkdir()
    _git(root, "init", "-q", "-b", "main")
    shutil.copy(CONFIG, root / ".pre-commit-config.yaml")
    return root


@pytest.fixture
def run_install(tmp_path: Path) -> RunInstall:
    bindir = tmp_path / "bin"
    bindir.mkdir()
    uv = bindir / "uv"
    uv.write_text(FAKE_UV, encoding="utf-8")
    uv.chmod(0o755)
    script = tmp_path / "install.sh"
    script.write_text(_install_body(), encoding="utf-8")

    def run(
        cwd: Path, *, hooks: str, install_exit: int = 0, **env: str
    ) -> subprocess.CompletedProcess[str]:
        environ = {
            k: v
            for k, v in os.environ.items()
            if k not in {"CI", "ALLOW_MISSING_GIT_HOOKS"} and not k.startswith("GIT_")
        }
        environ |= {
            "PATH": f"{bindir}{os.pathsep}{environ['PATH']}",
            "FAKE_INSTALL_HOOKS": hooks,
            "FAKE_INSTALL_EXIT": str(install_exit),
            **env,
        }
        return subprocess.run(  # noqa: S603 -- fixed argv, no shell
            ["bash", str(script)],  # noqa: S607 -- bash from PATH, as just runs the shebang
            cwd=cwd,
            env=environ,
            capture_output=True,
            text=True,
            check=False,
        )

    return run


def test_install_all_hooks_present_exits_zero(
    repo: Path, run_install: RunInstall
) -> None:
    result = run_install(repo, hooks="pre-commit pre-merge-commit")

    assert result.returncode == 0, result.stderr
    assert "Git hooks verified: pre-commit pre-merge-commit." in result.stdout


def test_install_one_hook_missing_exits_one_naming_it(
    repo: Path, run_install: RunInstall
) -> None:
    result = run_install(repo, hooks="pre-commit")

    assert result.returncode == 1
    assert "error: git hooks missing:" in result.stderr
    assert "hooks/pre-merge-commit" in result.stderr
    assert "hooks/pre-commit " not in result.stderr


@pytest.mark.parametrize(
    "env",
    [
        pytest.param({"CI": "true"}, id="ci-true"),
        pytest.param({"CI": "TRUE"}, id="ci-upper"),
        pytest.param({"ALLOW_MISSING_GIT_HOOKS": "1"}, id="allow-missing"),
    ],
)
def test_install_missing_hook_when_exempt_warns_and_exits_zero(
    repo: Path, run_install: RunInstall, env: dict[str, str]
) -> None:
    result = run_install(repo, hooks="pre-commit", install_exit=1, **env)

    assert result.returncode == 0, result.stderr
    assert "Warning: git hooks missing" in result.stderr
    assert "hooks/pre-merge-commit" in result.stderr


def test_install_failed_install_not_exempt_exits_nonzero(
    repo: Path, run_install: RunInstall
) -> None:
    result = run_install(repo, hooks="", install_exit=1)

    assert result.returncode != 0


def test_install_from_linked_worktree_checks_shared_hooks(
    repo: Path, run_install: RunInstall, tmp_path: Path
) -> None:
    _git(repo, "add", ".pre-commit-config.yaml")
    _git(
        repo, "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-m", "init"
    )
    worktree = tmp_path / "wt"
    _git(repo, "worktree", "add", "-q", str(worktree), "-b", "feature")
    (worktree / "sub").mkdir()

    result = run_install(worktree / "sub", hooks="pre-commit")

    assert result.returncode == 1
    assert f"{repo.resolve()}/.git/hooks/pre-merge-commit" in result.stderr.replace(
        str(repo), str(repo.resolve())
    )


def test_install_added_hook_type_not_installed_fails(
    repo: Path, run_install: RunInstall
) -> None:
    config = repo / ".pre-commit-config.yaml"
    config.write_text(
        config.read_text(encoding="utf-8").replace(
            "default_install_hook_types: [pre-commit, pre-merge-commit]",
            "default_install_hook_types: [pre-commit, pre-merge-commit, commit-msg]",
        ),
        encoding="utf-8",
    )

    result = run_install(repo, hooks="pre-commit pre-merge-commit")

    assert result.returncode == 1
    assert "hooks/commit-msg" in result.stderr


def test_install_outside_git_repository_skips_hooks(
    tmp_path: Path, run_install: RunInstall
) -> None:
    plain = tmp_path / "plain"
    plain.mkdir()

    result = run_install(plain, hooks="")

    assert result.returncode == 0
    assert "not a Git repository" in result.stdout
