name: Docs

on:
  push:
    branches: [main]
    paths:
      - "CONTRIBUTING.md"
      - "docs/**"
      - "mkdocs.yml"
      - "pyproject.toml"
      - "src/**"
      - "uv.lock"

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --group docs

      - name: Build docs strictly
        run: uv run mkdocs build --strict

      - name: Build & deploy
        run: uv run mkdocs gh-deploy --force
